<?php

namespace infoweb\cms\helpers;
use yii;

class CMS
{
    /**
     * Detects if the current request was generated by a form submit
     *
     * @return boolean
     */
    public static function formSubmitDetected()
    {
        if (Yii::$app->request->getIsPost()) {
            $post = Yii::$app->request->post();

            // If one of those 3 keys is set there was an actual form submit
            if (isset($post['save']) || isset($post['save-add']) || isset($post['save-close'])) {
                return true;
            }
        }

        return false;
    }
}